#application.properties
#minite calculate 
#https://www.google.com/search?q=milliseconds+to+min&oq=milliseconds+to+min&aqs=chrome..69i57.8631j0j7&sourceid=chrome&ie=UTF-8
user=admin	
password=password
timer=3600